version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    networks:
      - mysql

    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  mysql:
    driver: bridge
